# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "0.1.0"

package:
  name: onnxrt
  version: ${{ version }}

source:
  path: ../

build:
  script:
    # we bundle all the licenses of the dependencies into a THIRDPARTY.yml file and include it in the package
    - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
    - $BUILD_PREFIX/bin/maturin build -m ort-py/Cargo.toml
    - python -m pip install target/wheels/onnxrt*.whl -vv --no-deps --no-build-isolation --prefix=$PREFIX

requirements:
  build:
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin
    - onnxruntime-cpp
    - pip
  run:
    - numpy
    - onnxruntime-cpp
    - python

tests:
  - script:
      - python -c "import onnxrt"

about:
  homepage: https://github.com/killercup/cargo-edit
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: "A utility for managing cargo dependencies from the command line."
  summary: "A utility for managing cargo dependencies from the command line."
