repos:
-   repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        types: [file, rust]
        entry: cargo fmt -- --check
        pass_filenames: false

      - id: clippy
        name: clippy
        language: system
        types: [file, rust]
        entry: cargo clippy --bins --tests --examples --all -- -D warnings # Use -D warnings option to ensure the job fails when encountering warnings
        pass_filenames: false
