[project]
name = "ort"
version = "0.1.0"
description = "Add a short description here"
authors = ["Christian Bourjau <christian.bourjau@quantco.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
compilers = ">=1.7.0"
maturin = ">=1.4.0"
onnx = ">=1.15.0"
onnxruntime-cpp = ">=1.16.3"
pkg-config = ">=0.29.2"
python = ">=3.9"
rust = ">=1.76.0"
spox = ">=0.10.2"
jedi-language-server = ">=0.41.3,<0.42"
pytest = ">=8.0.2,<8.1"
pip = ">=24.0,<25"
ruff = ">=0.3.0,<0.4"
