[package]
name = "onnx_protos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
thiserror = "1.0.56"
protobuf = "3.4.0"

[build-dependencies]
protobuf-codegen = "3.4.0"
