[package]
name = "ort-py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "onnxrt"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
ort = { path = "../ort" }
ndarray = "0.15.6"
numpy = "0.20.0"
