# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "0.1.0"

package:
  name: onnxrt
  version: ${{ version }}

source:
  path: ../

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin
    - pip
    - python>=3.8
    - onnxruntime-cpp>=1.16
    - if: osx
      then:
        - libiconv
  run:
    # Version bound on Python removes it from the variant list - which is what we want
    - python>=3.8
    - if: osx
      then:
        - libiconv
    - numpy>=1.16.0
    - onnxruntime-cpp>=1.16
  ignore_run_exports:
    from_package:
      # Forward compatible C-API
      - onnxruntime-cpp

tests:
  - if: target_platform == build_platform
    then:
      - python:
          imports:
            - onnxrt
      - script:
        - pytest ./ort-py/tests

        # additional requirements at test time
        requirements:
          run:
            - pytest
            - spox

        files:
          # Extra files to be copied to the test directory from the "work directory"
          source:
            - ort-py/tests/

about:
  homepage: https://github.com/cbourjau/ort
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: "A PyO3 based wrapper around onnxruntime with the goal of becoming an independent ONNX runtime."
  summary: "A performant and user friendly ONNX runtime (based on onnxruntime)."
